### ISSUE TITLE
MINC paths stored in violation tables are absolute path in tmp dir

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris-MRI#401]
### Description

The MINC paths stored in the tables `MRICandidateErrors`, `mri_violations_log` and `mri_protocol_violated_scans` are actually absolute paths from the tmp directory when the pipeline was running and not the `/data/project/data/trashbin`. This is a horrible mistake of our pipelines.

Example: on my sandbox, my tmp directory is `/data/not_backed_up`, therefore, in all those tables, the paths stored are: `/data/not_backed_up/TarLoad-12-17-Z49MuF/file.mnc` but really, it should be modified to `trashbin/TarLoad-12-17-Z49MuF/file.mnc`.

### TODOs:
- [x] create an SQL patch that projects can run to fix their tables (replace tmp_dir by trashbin)
- [x] modify the LORIS-MRI scripts so they insert the paths relative to `data_dir`
- [x] check the MRI violations module to correct the code when trying to open the file in BB

### Labels for the future PRs

- minor
- BugFix
- "Add to release notes" 
- "Caveat for existing projects" explaining the importance of running the patch to correct their tables

**Comment by cmadjar** [comment]
PRs got merged
