### ISSUE TITLE
Ensure no duplicates can be inserted in the different violation tables

### ISSUE THREAD

**Issue by cmadjar** [aces/Loris-MRI#890]
# Description

Currently, the pipeline does not check whether a violation has already been inserted into LORIS before inserting a row in the violation tables. Affected tables:
- `mri_protocol_violated_scans`
- `mri_violations_log`
- `MRICandidateErrors`

Affected pipelines: dcm2bids python pipeline and dcm2mnc perl pipeline.

**TODOs:**
- [x] dcm2bids: see #884 for fixes to `mri_protocol_violated_scans` and `mri_violations_log`
- [x] dcm2bids: do the same for `MRICandidateErrors` https://github.com/aces/Loris-MRI/pull/891
- [x] perl pipeline: `MRICandidateErrors`, `mri_protocol_violated_scans` and `mri_violations_log`
- [x] SQL: add indexes or keys to ensure uniqueness in `MRICandidateErrors`, `mri_protocol_violated_scans` and `mri_violations_log` https://github.com/aces/Loris/pull/8382
- [x] SQL: add `PhaseEncodingDirection` and `EchoNumber` to `MRICandidateErrors` and modify on main the logic for duplicatas in `MRICandidateErrors` to include those two fields. https://github.com/aces/Loris/pull/8382
